# This is a basic workflow to help you get started with Actions

name: Hub and Spoke

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths: [ 'hub-spoke/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hub-spoke/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RESOURCE_GROUP: hub-spoke

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create Resource Group
      - name: resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -n ${{ env.RESOURCE_GROUP }} -l eastus2

      # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./hub-spoke/main.bicep
          parameters: deployVpnGateway=true vpnClientRootCert=${{ secrets.VPN_CLIENT_ROOT_CERT }}
          failOnStdErr: false
